M48
; DRILL file {KiCad (6.0.1)} date Tue Jan 25 15:54:27 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-01-25T15:54:27+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X78.19Y-100.0
X90.01Y-96.64
X92.019Y-109.906
X109.71Y-96.64
X122.03Y-99.99
T0
M30
